{% set name = "httpcore" %}
{% set version = "0.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6f30213335e34c1ade7be6ec7c47f19f50c56db36abef1a9dfa3815b1cb3888

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - h11 >=0.13,<0.15
    - h2 >=3,<5
    - sniffio ==1.*
    - anyio >=3.0,<5.0
    - certifi

test:
  requires:
    - pip
  imports:
    - httpcore
  commands:
    - pip check

about:
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.

extra:
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
